version: '3.8'
services:
  postgres_test:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agora_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: 